# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smartdocs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsmartdocs.proto\x12\tsmartdocs\"7\n\x15UploadDocumentRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\">\n\x16UploadDocumentResponse\x12\x13\n\x0b\x64ocument_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"6\n\x0eSearchResponse\x12\x14\n\x0c\x64ocument_ids\x18\x01 \x03(\t\x12\x0e\n\x06titles\x18\x02 \x03(\t\"-\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\"8\n\x0b\x41skResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x19\n\x11\x63ontext_documents\x18\x02 \x03(\t2\xd8\x01\n\nRagService\x12U\n\x0eUploadDocument\x12 .smartdocs.UploadDocumentRequest\x1a!.smartdocs.UploadDocumentResponse\x12=\n\x06Search\x12\x18.smartdocs.SearchRequest\x1a\x19.smartdocs.SearchResponse\x12\x34\n\x03\x41sk\x12\x15.smartdocs.AskRequest\x1a\x16.smartdocs.AskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smartdocs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_UPLOADDOCUMENTREQUEST']._serialized_start=30
  _globals['_UPLOADDOCUMENTREQUEST']._serialized_end=85
  _globals['_UPLOADDOCUMENTRESPONSE']._serialized_start=87
  _globals['_UPLOADDOCUMENTRESPONSE']._serialized_end=149
  _globals['_SEARCHREQUEST']._serialized_start=151
  _globals['_SEARCHREQUEST']._serialized_end=196
  _globals['_SEARCHRESPONSE']._serialized_start=198
  _globals['_SEARCHRESPONSE']._serialized_end=252
  _globals['_ASKREQUEST']._serialized_start=254
  _globals['_ASKREQUEST']._serialized_end=299
  _globals['_ASKRESPONSE']._serialized_start=301
  _globals['_ASKRESPONSE']._serialized_end=357
  _globals['_RAGSERVICE']._serialized_start=360
  _globals['_RAGSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
