# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import smartdocs_pb2 as smartdocs__pb2


class RagServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadDocument = channel.unary_unary(
                '/smartdocs.RagService/UploadDocument',
                request_serializer=smartdocs__pb2.UploadDocumentRequest.SerializeToString,
                response_deserializer=smartdocs__pb2.UploadDocumentResponse.FromString,
                )
        self.Search = channel.unary_unary(
                '/smartdocs.RagService/Search',
                request_serializer=smartdocs__pb2.SearchRequest.SerializeToString,
                response_deserializer=smartdocs__pb2.SearchResponse.FromString,
                )
        self.Ask = channel.unary_unary(
                '/smartdocs.RagService/Ask',
                request_serializer=smartdocs__pb2.AskRequest.SerializeToString,
                response_deserializer=smartdocs__pb2.AskResponse.FromString,
                )


class RagServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=smartdocs__pb2.UploadDocumentRequest.FromString,
                    response_serializer=smartdocs__pb2.UploadDocumentResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=smartdocs__pb2.SearchRequest.FromString,
                    response_serializer=smartdocs__pb2.SearchResponse.SerializeToString,
            ),
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=smartdocs__pb2.AskRequest.FromString,
                    response_serializer=smartdocs__pb2.AskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smartdocs.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smartdocs.RagService/UploadDocument',
            smartdocs__pb2.UploadDocumentRequest.SerializeToString,
            smartdocs__pb2.UploadDocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smartdocs.RagService/Search',
            smartdocs__pb2.SearchRequest.SerializeToString,
            smartdocs__pb2.SearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smartdocs.RagService/Ask',
            smartdocs__pb2.AskRequest.SerializeToString,
            smartdocs__pb2.AskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
